# Generated by Django 2.1.15 on 2020-05-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150)),
                ('checkOut_time', models.DateTimeField(blank=True, null=True)),
                ('checkIn_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.VisitFor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.Visitor'),
        ),
    ]
