# Generated by Django 2.1.15 on 2020-05-27 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_kwh', models.FloatField()),
                ('date_time_recorded', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MeterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metername', models.CharField(max_length=20)),
                ('meter_id', models.IntegerField()),
                ('meter_type', models.CharField(max_length=20)),
                ('meter_purpose', models.CharField(max_length=20)),
                ('meter_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='energydata',
            name='meter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_details', to='visitor_app.MeterDetail'),
        ),
    ]
