# Generated by Django 2.1.15 on 2020-05-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_auto_20200527_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=9112, verbose_name='Attribute Value')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Entity Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='energydata',
            name='meter_id',
        ),
        migrations.DeleteModel(
            name='EnergyData',
        ),
        migrations.DeleteModel(
            name='MeterDetail',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='visitor_app.Entity'),
        ),
    ]
